name: desafio_modulo_avancado
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  mysql1: ^0.17.1

dev_dependencies:
  pedantic: ^1.9.0
